"""add ckan_verify_ssl to user

Revision ID: 2f3e4d5c6b7a
Revises: 1f2e3d4c5b6a
Create Date: 2026-02-19 16:26:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f3e4d5c6b7a'
down_revision = '1f2e3d4c5b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.add_column('user', sa.Column('ckan_verify_ssl', sa.Boolean(), nullable=False, server_default=sa.text('1')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust ###
    op.drop_column('user', 'ckan_verify_ssl')
    # ### end Alembic commands ###
